nosql_creds:
  mongo_inst:
    username: "root"
    host: "mongodb"
    port: 27017
    db_name: "development"
    min_pool_size: 10
    max_pool_size: 50

databases:
  dev-primary:
    system: sqlite
    database: "./data/kubeplayground.db"

redis:
  host: "redis"
  port: 6379
  db: 0
  draft_ttl: 604800   # 7 days in seconds
  namespace_ttl: 86400  # 24 hours in seconds
